---
title: "Imprint/Provider Identification"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


**The following provides mandatory data concerning the provider of this website, obligations with regard to data protection, as well as other important legal references involving this Internet site (= scienceofboosting.org) of the Max Planck Institute for Human Development as required by German law.**


## Provider
The provider of this Internet site within the legal meaning of the term is the registered association Max Planck Society for the Advancement of Science e.V.

## Address
Max-Planck-Gesellschaft zur Förderung der Wissenschaften e.V.<br>
Hofgartenstrasse 8<br>
D-80539 Munich<br>
Germany<br>
Phone: +49 89 2108-0<br>
Internet: https://www.mpg.de<br>


## Register of Societies and Associations
The Max Planck Society is registered in the Official Register of Societies and Associations at Berlin-Charlottenburg Local Court under the register number VR 13378 B.


## Representatives
The Max Planck Society is legally represented by its Board of Directors which, in turn, is represented by the President of the Society, Prof. Dr. Martin Stratmann and by Secretary General Rüdiger Willems.


## Value Added Tax Identification Number
The value added tax identification number of the Max Planck Society is DE 129517720.

## Editors
Responsible editor for the contents of the Max Planck Society's website with regard to media law:

Dr. Anastasia Kozyreva <br>
Max Planck Institute for Human Development <br>
Lentzeallee 94<br>
14195 Berlin<br>
Germany<br>



## Legal Structure
The Max Planck Society is a non-profit research facility which is organized as a registered association. All of the institutes and facilities of the Max Planck Society are largely autonomous in terms of organization and research, but as a rule have no legal capacity of their own.


## Foreign Language Pages
To the extent that parts of this Internet site are offered in languages other than German, this represents a service exclusively for staff and guests of the Max Planck Society who are not proficient in German.


## Liability for Contents of Online Information
As the provider of contents in accordance with Section 7 Paragraph 1 of the Tele-Media Law, the Max Planck Society shall be responsible for any contents which it makes available for use in accordance with general legal provisions. The Max Planck Society makes every effort to provide timely and accurate information on this Website. Nevertheless, errors and inaccuracies cannot be completely ruled out. Therefore, the Max Planck Society does not assume any liability for the relevance, accuracy, completeness or quality of the information provided. The Max Planck Society shall not be liable for damage of a tangible or intangible nature caused directly or indirectly through the use or failure to use the information offered and/or through the use of faulty or incomplete information unless it is verifiably culpable of intent or gross negligence. The same shall apply to any downloadable software available free of charge. The Max Planck Society reserves the right to modify, supplement, or delete any or all of the information offered on its Internet site, or to temporarily or permanently cease publication thereof without prior and separate notification.


## Links to Internet Sites of Third Parties
This Internet site includes links to external pages. These external links are designated as follows: {{< icon name="external-link-alt" pack="fas" >}}.
The respective provider shall be responsible for the contents of any linked external pages. However, a constant review of linked external pages is unreasonable without concrete reason to believe that a violation of the law may be involved. If the Max Planck Society determines such or it is pointed out by others that an external offer to which it is connected via a link entails civil or criminal responsibility, then the Max Planck Society will immediately eliminate any link to this offer. The Max Planck Society expressly dissociates itself from such contents.


## Copyright
Any contents on this website are protected by copyright law.

<i class="far fa-copyright"></i> Max-Planck-Gesellschaft zur Förderung der Wissenschaften e.V., Munich. All rights reserved.

The website was build using the Academic theme for Hugo: MIT License (MIT) Copyright <i class="far fa-copyright"></i>  2016-present George Cushen. 

<!--
Header on homepage: piqsels.com – License: Creative Commons Zero - CC0

Favicon: PNGGuru – License: non-commercial use, no attribution required. 
-->
[Privacy policy](https://ai_society.mpib.dev/intervention_toolbox/privacy.html) - [Imprint/Provider Identification](https://ai_society.mpib.dev/intervention_toolbox/terms.html)

```{css, echo=FALSE}

p {
 font-size: 16px;
 width: 1400px;
  margin: 10px 15px 15px 0px;
 }



li {
  font-size: 20px;
  }



h1 {
  font-size: 32px;
  width: 1400px;
}



body {
  # background-color: rgba(176, 219, 234, 0.5);
   <!-- margin-top: 10px; -->
  <!-- margin-left: 5px; -->
 padding-left: 0px;
   width: 50%;
}

.btn-workflowr {
  display: none
}


.btn-workflowr-sessioninfo {
  visibility: hidden
}

.btn-default {
  visibility: hidden
}

.package-detail {
  padding: 24px;
  box-shadow: inset 0 1px 3px #dbdbdb;
  background: hsl(213, 20%, 99%);
}

.detail-label {
  margin: 20px 0 4px;  
  font-size: 14px;
  color: rgba(0, 0, 0, 0.6);
}

.detail-header {
  margin-bottom: 16px;
  font-size: 20px;
  font-weight: 600;
}

.detail-title {
  margin-left: 18px;
  font-size: 14px;
  font-weight: 400;
  color: rgba(0, 0, 0, 0.6);
}

.detail-description {
  font-size: 14px;
}

.archived-table {
  border: 1px solid hsl(213, 33%, 93%);
  border-radius: 4px;
  box-shadow: 0 2px 7px 0 rgba(0, 0, 0, 0.05);
  font-size: 14px;
}


```
